config/routes.rb
YarnMatch::Application.routes.draw do
  resources :yarns
  authenticated :user do
    root :to => 'home#index'
  end
  root :to => "home#index"
  devise_for :users
  scope '/admin' do
    resources :users
  end
end

app/models/yarn.rb
class Yarn
  include Mongoid::Document
  field :brand, type: String
  field :name, type: String
  field :cyc_weight, type: Integer
  field :name_weight, type: String
  field :ply_weight, type: Integer
  field :wpi_weight, type: Integer
  field :knit_weight, type: Integer

  #before_validation :calculate_weights

  validate :name_weight_inclusion

  #def calculate_weights
    
  #end
  
  def name_weight_inclusion
    errors.add(:name_weight) unless Yarn.name_weights.include?(name_weight)
  end

  def self.name_weights
    ['Thread', 'Cobweb', 'Lace', 'Light Fingering', 'Fingering', 'Sport', 'DK',
     'Worsted', 'Aran', 'Bulky', 'Super Bulky']
  end
end

app/controllers/yarns_controller.rb
class YarnsController < ApplicationController

  before_filter :authenticate_user!
  load_and_authorize_resource

  # GET /yarns
  # GET /yarns.json
  def index
    @yarns = Yarn.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @yarns }
    end
  end

  # GET /yarns/1
  # GET /yarns/1.json
  def show
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @yarn }
    end
  end

  # GET /yarns/new
  # GET /yarns/new.json
  def new
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @yarn }
    end
  end

  # GET /yarns/1/edit
  def edit
  end

  # POST /yarns
  # POST /yarns.json
  def create
    respond_to do |format|
      if @yarn.save
        format.html { redirect_to @yarn, notice: 'Yarn was successfully created.' }
        format.json { render json: @yarn, status: :created, location: @yarn }
      else
        format.html { render action: "new" }
        format.json { render json: @yarn.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /yarns/1
  # PUT /yarns/1.json
  def update
    respond_to do |format|
      if @yarn.update_attributes(params[:yarn])
        format.html { redirect_to @yarn, notice: 'Yarn was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @yarn.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /yarns/1
  # DELETE /yarns/1.json
  def destroy
    @yarn.destroy
    respond_to do |format|
      format.html { redirect_to yarns_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/yarns_helper.rb
module YarnsHelper
end

app/views/yarns/_form.html.haml
= simple_form_for(@yarn) do |f|
  = f.error_notification

  .form-inputs
    .row
      .columns.large-3
        = f.input :brand
      .columns.large-3
        = f.input :name
      .columns.large-6
    .row
      .columns.large-3
        = f.input :cyc_weight, as: :integer, label: 'Craft Yarn Council Weight'
    .row
      .columns.large-3
        = f.input :name_weight, as: :select, collection: Yarn.name_weights
    .row
      .columns.large-3
        = f.input :ply_weight, as: :integer
    .row
      .columns.large-3
        = f.input :wpi_weight, as: :integer, label: 'Wraps Per Inch Weigth'
    .row
      .columns.large-3
        = f.input :knit_weight, as: :integer

  .form-actions
    .row
      .columns.large-3
        = f.button :submit
      .columns.large-9

app/views/yarns/edit.html.haml
%h1 Editing yarn

= render 'form'

= link_to 'Show', @yarn
\|
= link_to 'Back', yarns_path

app/views/yarns/index.html.haml
%h1 Listing yarns

%table
  %tr
    %th Brand
    %th Name
    %th Cyc weight
    %th Name weight
    %th Ply weight
    %th Wpi weight
    %th Knit weight
    %th
    %th
    %th

  - @yarns.each do |yarn|
    %tr
      %td= yarn.brand
      %td= yarn.name
      %td= yarn.cyc_weight
      %td= yarn.name_weight
      %td= yarn.ply_weight
      %td= yarn.wpi_weight
      %td= yarn.knit_weight
      %td= link_to 'Show', yarn
      %td= link_to 'Edit', edit_yarn_path(yarn)
      %td= link_to 'Destroy', yarn, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Yarn', new_yarn_path

app/views/yarns/new.html.haml
%h1 New yarn

= render 'form'

= link_to 'Back', yarns_path

app/views/yarns/show.html.haml
%p#notice= notice

%p
  %b Brand:
  = @yarn.brand
%p
  %b Name:
  = @yarn.name
%p
  %b Cyc weight:
  = @yarn.cyc_weight
%p
  %b Name weight:
  = @yarn.name_weight
%p
  %b Ply weight:
  = @yarn.ply_weight
%p
  %b Wpi weight:
  = @yarn.wpi_weight
%p
  %b Knit weight:
  = @yarn.knit_weight

= link_to 'Edit', edit_yarn_path(@yarn)
\|
= link_to 'Back', yarns_path